// <auto-generated/>

using System;
using FluentNetBDD.Dsl;
using FluentNetBDD.Tests.Dsl.UserFeatures;



namespace FluentNetBDD.Tests.Generating.Generated;

#nullable enable

public interface IAgileNamedUserGivenUserDriver : IUserWithName, IUserWithAgility { }
public interface IAgileNamedUserGivenDriver
{
    IAgileNamedUserGivenUserDriver User { get; }
}

public interface IAgileNamedUserWhenUserDriver : IUserGreetingAction, IUserAgilityActions { }
public interface IAgileNamedUserWhenDriver
{
    IAgileNamedUserWhenUserDriver User { get; }
}

public interface IAgileNamedUserThenUserDriver : IUserGreetingVerification, IUserAgilityVerification { }
public interface IAgileNamedUserThenDriver
{
    IAgileNamedUserThenUserDriver User { get; }
}



public partial class AgileNamedUserDsl : Dsl<IAgileNamedUserGivenDriver, IAgileNamedUserWhenDriver, IAgileNamedUserThenDriver>
{
    public AgileNamedUserDsl(IServiceProvider provider) : base(provider)
    {
    }
}

#nullable restore