using FluentNetBDD.Generation;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage(
    "RoslynDiagnostics",
    "RS1041:Do not use obsoleted APIs",
    Justification = "Suppression is necessary for this project.")]

namespace FluentNetBDD.Generators
{
    [Generator]
    public sealed class MinimalGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
//#if DEBUG
//            if (!Debugger.IsAttached) Debugger.Launch();
//#endif
            
            var classNames = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (n, _) => n is AttributeSyntax,
                    transform: (ctx, _) =>
                    {
                        var attr = (AttributeSyntax)ctx.Node;
                        var symbol = ctx.SemanticModel.GetSymbolInfo(attr).Symbol as IMethodSymbol;
                        return attr.ArgumentList != null && 
                               attr.ArgumentList.Arguments.Any() &&
                               symbol != null && 
                               symbol.ContainingType.Name == nameof(GenerateMarkerAttribute)
                            ? attr.ArgumentList.Arguments.Select(x => x.ToString()).ToArray()
                            : null;
                    })
                .Where(n => n != null && n.Length >= 1 && n[0] != null)
                .Select((n, _) => n)
                .Collect();

            context.RegisterSourceOutput(classNames, (spc, markers) =>
            {
                foreach(var marker in markers.Distinct(new FirstIndexComparer()))
                {
                    var className = marker[0].Trim('"');
                    var value = marker.Length > 1 ? marker[1].Trim('"') : null;
                    value = value ?? "Hello world";
                    spc.AddSource($"{className}.g.cs", $"// <auto-generated/>\npublic class {className} {{ public override string ToString() {{ return \"{value}!\"; }} }}");
                }
            });
        }
    }

    public class FirstIndexComparer : IEqualityComparer<string[]>
    {
        public bool Equals(string[] x, string[] y)
        {
            if (x == null || y == null || x.Length < 1 || y.Length < 1)
            {
                return false;
            }
            return x[0].Equals(y[0]);
        }

        public int GetHashCode(string[] obj)
        {
            return obj[0].GetHashCode();
        }
    }
}